name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - feature
      - research
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '🧰 Maintenance'
    labels:
      - refactor
      - security
      - performance
  - title: '🔧 DevOps'
    labels:
      - devtools
      - documentation
      - cicd
      - observability
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
prerelease: true # default to prerelease rather than full release for new drafts
include-pre-releases: true # include pre-releases in determining the latest version
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - feature
  patch:
    labels:
      - patch
      - bug
      - security
      - performance
      - refactor
  default: patch
template: |
  ## Changes

  $CHANGES
