"""empty message

Revision ID: 710e9d0aa52c
Revises: 11c7d4579574
Create Date: 2026-02-04 16:23:47.471517

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '710e9d0aa52c'
down_revision: Union[str, None] = '11c7d4579574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_task_run_id_task_type_id_created_at_desc', 'task_run', ['id', 'task_type_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_task_run_type_created_at_desc', 'task_run', ['task_type_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_run_type_created_at_desc', table_name='task_run')
    op.drop_index('idx_task_run_id_task_type_id_created_at_desc', table_name='task_run')
    # ### end Alembic commands ###
