"""empty message

Revision ID: 8074f58ce89a
Revises: 78bc377e8724
Create Date: 2025-10-09 14:05:12.953357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8074f58ce89a'
down_revision: Union[str, None] = '78bc377e8724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_type', sa.Column('parameters_spec', sa.VARCHAR(), nullable=True))
    op.add_column('task_type', sa.Column('result_spec', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_type', 'result_spec')
    op.drop_column('task_type', 'parameters_spec')
    # ### end Alembic commands ###
