"""empty message

Revision ID: 807d2501c8e4
Revises: b9d7d81aaf35
Create Date: 2025-06-11 12:26:41.042439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '807d2501c8e4'
down_revision: Union[str, None] = 'b9d7d81aaf35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_run_parent_task_uuid'), 'task_run', ['parent_task_uuid'], unique=False)
    op.create_index(op.f('ix_task_run_task_type_id'), 'task_run', ['task_type_id'], unique=False)
    op.create_index(op.f('ix_task_run_state_transition_task_uuid'), 'task_run_state_transition', ['task_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_run_state_transition_task_uuid'), table_name='task_run_state_transition')
    op.drop_index(op.f('ix_task_run_task_type_id'), table_name='task_run')
    op.drop_index(op.f('ix_task_run_parent_task_uuid'), table_name='task_run')
    # ### end Alembic commands ###
