"""empty message

Revision ID: bc498857ff1c
Revises: 710e9d0aa52c
Create Date: 2026-02-04 16:56:45.508034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bc498857ff1c'
down_revision: Union[str, None] = '710e9d0aa52c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_task_run_type_state_since_desc', 'task_run', ['task_type_id', sa.literal_column('state_since DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_run_type_state_since_desc', table_name='task_run')
    # ### end Alembic commands ###
