apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app: pyfilament-redis
  includeSelectors: true
  includeTemplates: true

resources:
- statefulset.yaml
- service.yaml