apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pyfilament-psql
spec:
  serviceName: pyfilament-psql
  replicas: 1
  selector:
    matchLabels:
      component: psql
  template:
    metadata:
      labels:
        component: psql
    spec:
      containers:
        - name: psql
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: pyfilament
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: psql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: psql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: ebs-gp3
