"""empty message

Revision ID: 11c7d4579574
Revises: 8074f58ce89a
Create Date: 2026-01-30 15:15:47.676950

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '11c7d4579574'
down_revision: Union[str, None] = '8074f58ce89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'idx_task_run_id_task_type_id_created_at', 'task_run', ['id', 'task_type_id', 'created_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_run_id_task_type_id_created_at', table_name='task_run')
    # ### end Alembic commands ###
