"""empty message

Revision ID: 3e2df1e9f806
Revises: 99538300054a
Create Date: 2025-04-17 20:17:24.545278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3e2df1e9f806'
down_revision: Union[str, None] = '99538300054a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'task_type', ['func_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_type', type_='unique')
    # ### end Alembic commands ###
