"""empty message

Revision ID: 78bc377e8724
Revises: 807d2501c8e4
Create Date: 2025-07-14 19:12:10.264182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '78bc377e8724'
down_revision: Union[str, None] = '807d2501c8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_task_run_state_since', 'task_run', ['state_since'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_run_state_since', table_name='task_run')
    # ### end Alembic commands ###
