"""empty message

Revision ID: 99538300054a
Revises: 
Create Date: 2025-04-07 21:34:44.486218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '99538300054a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('func_address', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('task_uuid', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.VARCHAR(), nullable=False),
    sa.Column('state_since', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('heartbeat', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('parent_task_uuid', sa.VARCHAR(), nullable=True),
    sa.Column('parameters_json', sa.VARCHAR(), nullable=True),
    sa.Column('result_json', sa.VARCHAR(), nullable=True),
    sa.Column('task_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_uuid'], ['task_run.task_uuid'], ),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_uuid')
    )
    op.create_table('task_run_state_transition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_uuid', sa.VARCHAR(), nullable=False),
    sa.Column('from_state', sa.VARCHAR(), nullable=False),
    sa.Column('to_state', sa.VARCHAR(), nullable=False),
    sa.Column('state_since', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_uuid'], ['task_run.task_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_run_state_transition')
    op.drop_table('task_run')
    op.drop_table('task_type')
    # ### end Alembic commands ###
