"""empty message

Revision ID: b9d7d81aaf35
Revises: 3e2df1e9f806
Create Date: 2025-05-15 19:48:39.964873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b9d7d81aaf35'
down_revision: Union[str, None] = '3e2df1e9f806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_task_run_created_at', 'task_run', ['created_at'], unique=False)
    op.create_index('idx_task_run_state', 'task_run', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_run_state', table_name='task_run')
    op.drop_index('idx_task_run_created_at', table_name='task_run')
    # ### end Alembic commands ###
