apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: pyfilament-examples

resources:
- cronjob.yaml
images:
- name: ghcr.io/pyfilament/pyfilament
  newTag: 0.0.17
